version: '3'
services:
  netdata_monitor:
    image: manoskoutoulakis/netdata_nginx:latest
    environment:
      - ID=${NETDATA_ID}
      - REV_PORT=${NETDATA_MONITORING_PORT}
    ports:
      - "${NETDATA_MONITORING_PORT}:${NETDATA_MONITORING_PORT}"
    logging:
      driver: none
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: "${EXECUTOR_INSTANCE}-OBC-Resource-Monitoring"
    
  postgres:
    image: postgres:9.6
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${EXECUTOR_DB_PORT}:5432"
    container_name: "${EXECUTOR_INSTANCE}-OBC-DB"

  airflowserver:
    image: manoskoutoulakis/obc-cwl-airflow:1.10.10
    restart: always
    environment:
      #Airflow configuration
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080/${OBC_USER_ID}
      - LOAD_EX=n
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
      #OBC Client environment variables
      - NETDATA_ID=${NETDATA_ID}
      - OBC_USER_ID=${OBC_USER_ID}
      - PUBLIC_IP=${PUBLIC_IP}
      - EXECUTOR_INSTANCE=${EXECUTOR_INSTANCE}
      - EXECUTOR_DB_PORT=${EXECUTOR_DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NETDATA_MONITORING_PORT=${NETDATA_MONITORING_PORT}
      - OBC_EXECUTOR_PORT=${OBC_EXECUTOR_PORT}
      - OBC_AIRFLOW_PORT=${OBC_WMS_PORT}
      - EXECUTOR_DB_PORT=${EXECUTOR_DB_PORT}
      - WORKFLOW_FORMAT=${WORKFLOW_FORMAT}

    volumes:
      # Folder where airflow should store files
      - dagvolume:/usr/local/airflow/dags
      - logvolume:/usr/local/airflow/logs
      - reportvolume:/usr/local/airflow/REPORTS
      # Configuration File
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg
      - /var/run/docker.sock:/var/run/docker.sock
      # For custom plugins
      #- ./plugins:/usr/local/airflow/plugins
    ports:
      - "${OBC_WMS_PORT}:8080"
      - "${OBC_EXECUTOR_PORT}:5000"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 15s
      timeout: 15s
      retries: 3
    container_name: "${EXECUTOR_INSTANCE}-OBC-${WORKFLOW_FORMAT}"
volumes:
  # Dag volumes 
  dagvolume:
  logvolume:
  reportvolume:  
